### ISSUE TITLE
French language?

### ISSUE THREAD

**Issue by AlexandreCA** [InoUno/xi-tinkerer#13]
Hi Ino! I would like to know when XI Tinkerer will support the French language. I’m trying to translate the client as best as I can, but the program doesn’t really handle accents. According to ChatGPT, this could be where the issue lies. My YAML files are already translated; I just need to reconvert them into valid .DAT files.

**Comment by InoUno** [comment]
It will be supported when someone figures out how the encoding for it works, and if/how the client can even handle the French language setting still, since it's been discontinued as far as I know.

Unfortunately, it's at the very bottom of my to-do list, and thus I'm not going to be looking into it any time soon.

**Comment by AlexandreCA** [comment]
No problem, I found a new way! Thanks!
